export const REDACTION_VALUE = "[REDACTED]";

export const SENSITIVE_LOG_PATHS = [
  "password",
  "*.password",
  "**.password",
  "secret",
  "*.secret",
  "**.secret",
  "authorization",
  "*.authorization",
  "**.authorization",
  "cookie",
  "*.cookie",
  "**.cookie",
  "accessToken",
  "*.accessToken",
  "**.accessToken",
  "refreshToken",
  "*.refreshToken",
  "**.refreshToken",
  "apiKey",
  "*.apiKey",
  "**.apiKey",
  "nik",
  "*.nik",
  "**.nik",
  "nationalId",
  "*.nationalId",
  "**.nationalId",
  "phone",
  "*.phone",
  "**.phone",
  "email",
  "*.email",
  "**.email",
  "rawPayload",
  "*.rawPayload",
  "**.rawPayload",
] as const;
