-- migration-safety: allow-destructive ADR-016
ALTER TABLE audit_events DROP CONSTRAINT audit_events_action_check;
ALTER TABLE audit_events ADD CONSTRAINT audit_events_action_check CHECK (action IN (
  'CASE_MEMBERSHIP_GRANTED', 'CASE_MEMBERSHIP_REVOKED', 'SENSITIVE_FIELD_VIEW',
  'SENSITIVE_FIELD_MATCH', 'EVIDENCE_EXPORT_AUTHORIZATION',
  'SOURCE_ACCESS_AUTHORIZATION', 'CANDIDATE_RESOLUTION', 'ENTITY_MERGE',
  'ENTITY_MERGE_REVERSE'
));
